version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=anhle3720
      - MYSQL_DATABASE=bookstore
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=anhle3720
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_HOST=% # Cho phép kết nối từ bất kỳ host nào
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
